#' function that generates the scripts
#'
#' @keywords internal
#' @noRd
gen_script <- function(datapath_conv, datapath_local, suf_version, dataformat, subformat, datalist, prio, english, set_missings, parallel, further_training, education, children, work_exp, unemp_exp){
      sc <- toupper(identify_sc(datapath_conv))
      # if prio tab hasnt been clicked, we want to load the static element from constants. if prio is clicked we use the inputs returned value. This is necessary because inputs often do not return their return value when they are hidden behind a tab that wasnt clicked yet.
      if (is.null(prio) || length(prio) == 0) {
        prio <- if (sc != "SC5") .labels_sc3_4_6 else .labels_sc5
      }
      prio_var <- as.numeric(stringr::str_extract_all(prio, "\\d{2}"))

      if(dataformat== "R" & subformat == "Harmonized Spell Format"){
        chapter <- 6 + length(datalist) # fixed number of chapters for main person-year-dataset preparation
        scripts <- c(
          paste0("# NEPScribe R base script to transform NEPS ", sc, " SUF data into a person-year format."),
          "",
          "# This is a basic data preparation script that generates a dataset in a person-year-format by taking the harmonized spells from the NEPS SUF Biography file as a baseline.",
          "# Please carefully check each line and make sense of it. Edits to the script that fit your research project’s needs are probably necessary and recommended.",
          "# !ATTENTION!",
          "# If you want access to within spell variation across waves, spell related longitudinal information should be joined via 'ID_t', 'wave' and 'splink' after step 6, when the person-year structure has been generated and after dropping harmonized episodes in the spell files.",
          "# When using the 'Additional variables' function in the NEPScribe app, this procedure is applied automatically. This ensures that time-varying spell information is preserved. However, it requires careful handling of different missing value codes that arise from filtering or data issues.",
          "",
          "# Approach:",
          "",
          "# 1. Step: Load the Biography dataset as a base for the person-year-dataset and compile start and end date and generate a duration variable.",
          "",
          "# 2. Step: Load the Employment dataset and merge it to the biography dataset to access the working hours variable. This variable will be used in step 5 for the prioritisation of parallel employment episodes.",
          "",
          "# 3. Step: Load the VocTrain dataset and merge it to the biography dataset to access the vocational training type variable. This variable will also be used in the spell prioritisation process.",
          "",
          "# 4. Step: Expand the data to a monthly format by multiplying each row of each respondent with the spell length in month (dur variable). This expansion to a month format is needed since there is no wave-specific information for episodes in the biography file but only one observation per episode with start and end date. To identify which episode represents the main activity at each interview date (and therefore wave) this reshape is needed. It serves as the basis for the spell prioritisation process in the next step.",
          "",
          "# 5. Step: Spell prioritisation process. Sort the months of each respondent by determined spell order, main/side episode (descending), working hours (descending), duration (descending) and splink (ascending order in which the episodes were reported). You may edit this according to your research question(s).",
          "",
          "# 6. Step: Reduce rows in dataset to interview date months by loading the CohortProfile dataset and generating a month variable for each interview date. Then merge this dataset and the biography data by ID_t and month. This leads to a dataset with one row per wave of each respondent (what we call: 'person-year-dataset').",
          "",
          "# Additional data preparation steps may vary based on the settings configured in the Transform Data tab of the NEPScribe app.",
          "",
          "# Package Information and Script Formatting:",
          "# Script uses mostly dplyr due to its simplicity and sometimes base R for performance reasons. ",
          "# The code might need new indentation and formatting: Try Strg+A and then Strg+Shift+A in RStudio.",
          "",
          "rm(list = ls())",
          "",
          "# Packages ----------------------------------------------------------------",
          "list.of.packages <- c('dtplyr','haven','dplyr','tidyr','janitor','readstata13','stringr', 'remotes')",
          "new.packages <- list.of.packages[!(list.of.packages %in% installed.packages()[,'Package'])] # check if required packages are in installed packages on this machine",
          "if(length(new.packages)) install.packages (new.packages) # if new.packages contains sth and thus length is > 0, install those new packages",
          "",
          "# Install nepstools if not installed (package needs to be installed seperately from github) ",
          "if(!'nepstools' %in% installed.packages()) {",
          " remotes::install_github('a-helbig/nepstools')",
          "}",
          "",
          "# Add nepstools to list.of.packages",
          "list.of.packages <- append(list.of.packages, 'nepstools')",
          "invisible(lapply(list.of.packages, library, character.only = TRUE))",
          "",
          if(nchar(datapath_local)>0) paste0("datapath = ","'",datapath_local,"/","'"),
          if(nchar(datapath_local)==0)"datapath = \"\" # Specify local datapath here",
          if(nchar(datapath_local)>0) paste0("suf_version = ", "'", suf_version,"'", " # Please adjust if necessary"),
          if(nchar(datapath_local)==0)"suf_version = \"16-0-0\" # Please adjust if necessary",
          paste0("english = ", english),
          paste0("sc = ", "'",sc,"'"),
          "",
          "# 1. Base: Biography file ---------------------------------------------------------------------",
          "",
          "# We take the harmonized episodes from the biography file as a baseline for our person-year dataset.",
          "",
          "bio <- read_neps(paste0(datapath, '/', sc, '_Biography_D_', suf_version,'.dta'), english = english) |> ",
          "  replace_values_with_na() # We need to set missings in the biography data to get only positive values in the duration variable ('dur') generated in the next step. We need this 'dur' variable later for expanding the dataset to a monthly structure", #- in contrast we wont set missings in employment and voctrain data in order to get the same prioritisation as in stata and to preserve the possibility in stata to have extended missings (these extended missings otherwise would have an impact on the ordering in stata prep compared to Rs prep)
          "",
          "# Generate episode dates variables: transform date vars to one variable in the format: 'months since 1960' and get rid of episodes with missing date values. ",
          "bio <- bio |> ",
          "  mutate(start=((starty-1960)*12)+startm-1,",
          "         end=((endy-1960)*12)+endm-1,",
          "         dur = end-start+1)  |> ",
          "  filter(!is.na(start) & !is.na(end)) |> ",
          "  select(-startm,-starty,-endm,-endy)",
          "",
          "# Assign varlabels to variables",
          if(english)"attr(bio$start, 'label') <- 'Start date'",
          if(english)"attr(bio$end, 'label') <- 'End date'",
          if(english)"attr(bio$dur, 'label') <- 'Duration'",
          if(!english)"attr(bio$start, 'label') <- 'Startdatum'",
          if(!english)"attr(bio$end, 'label') <- 'Enddatum'",
          if(!english)"attr(bio$dur, 'label') <- 'Dauer'",
          "",
          "# 2. Employment info for spell prioritisation ---------------------------------------------------------------------",
          "",
          "# We need the working hours for the prioritisation process of parallel employment spells later in Step 5. Thus we join employment data, recode working hours and reduce to harmonized episodes (subspell==0) and join it to biography data.",
          if(sc == "SC6") "cols <- c('ID_t', 'splink', 'spell','subspell', 'ts23223_g1')"
          else "cols <- c('ID_t', 'splink', 'spell','subspell', 'ts23223')",
          "",
          "# Read NEPS dataset with nepstools::read_neps()",
          "emp <- read_neps(paste0(datapath, '/', sc, '_spEmp_D_', suf_version,'.dta'), col_select = cols, english = english) |>",
          "  filter(subspell == 0) ",
          "",
          if (sc == "SC6")  "emp <- emp |> ",
          if (sc == "SC6")    "rename(ts23223 = ts23223_g1)",
          "",
          "emp$ts23223[emp$ts23223 == -21] <- NA # work time not specified",
          "emp$ts23223[emp$ts23223 == -20] <- 90 # more than 90 hours per week",
          "",
          "bio <- left_join(bio, emp, by=c('ID_t', 'splink'))",
          "rm(emp)",
          "",
          "# 3. Vocational Training Preparation for spell prioritisation -----------------------------------------",
          "",
          if(sc == "SC6")"# We also require the type of vocational training for the prioritisation process of vocational training spells later in Step 4. Thus we join voctrain data, recode type of voc. training (different variable in Wave 1: ts15201_v1), reduce to harmonized episodes (subspell==0) and join it to biography data.",
          if(sc == "SC6")"suppressWarnings({ # warnings are suppressed here because case_match throws a warning due to conflicting variable labels in ts15201 and ts15201_v1. This doesnt matter, because in the new variable 'vt_typ' the variable labels from ts15201 are being used and that is preferable in most cases. Change this if neccessary.",
          if(sc == "SC6")"voctrain <- read_neps(paste0(datapath, '/', sc, '_spVocTrain_D_', suf_version,'.dta'), col_select = c('ID_t', 'splink', 'subspell', 'ts15201_v1', 'ts15201'), english = english) |> ",
          if(sc == "SC6")"  mutate(ts15201_v1 = case_match(ts15201_v1, # here the codes from the old voctrain-type var from wave 1 (ts15201_v1) are aligned with the new voctrain-type var ts15201 from wave 2+",
          if(sc == "SC6")"  2 ~ 3, ",
          if(sc == "SC6")"  3 ~ 4, ",
          if(sc == "SC6")"  4 ~ 5, ",
          if(sc == "SC6")"  5 ~ 6, ",
          if(sc == "SC6")"  6 ~ 9, ",
          if(sc == "SC6")"  7 ~ 10, ",
          if(sc == "SC6")"  8 ~ 15, ",
          if(sc == "SC6")"  9 ~ 16, ",
          if(sc == "SC6")"  10 ~ 11, ",
          if(sc == "SC6")"  11 ~ 12, ",
          if(sc == "SC6")"  12 ~ 13, ",
          if(sc == "SC6")"  13 ~ 14, ",
          if(sc == "SC6")"  14 ~ 17,",
          if(sc == "SC6")"  .default = ts15201_v1),",
          if(sc == "SC6")"  # Replace vttyp with recoded ts15201_v1 where vttyp is -54 (wave 1)",
          if(sc == "SC6")"  vt_typ = ts15201,",
          if(sc == "SC6")"  vt_typ = if_else(vt_typ == -54, ts15201_v1, vt_typ)) |>",
          if(sc == "SC6")"  filter(subspell == 0) |> ",
          if(sc == "SC6")"  select(-ts15201,-ts15201_v1, -subspell)",
          if(sc == "SC6")"})",
          if(sc %in% c("SC3","SC4","SC5"))"# We also require the type of vocational training for the prioritisation process of spells later in Step 5. Thus we join voctrain data, reduce to harmonized episodes (subspell==0) and join it to biography data.",
          if(sc %in% c("SC3","SC4","SC5")) "voctrain <- read_neps(paste0(datapath, '/', sc, '_spVocTrain_D_', suf_version,'.dta'), english = english, col_select = c('ID_t', 'splink','subspell', 'ts15201')) |> ",
          if(sc %in% c("SC3","SC4","SC5"))"mutate(vt_typ = ts15201) |> ",
          if(sc %in% c("SC3","SC4","SC5"))"filter(subspell == 0) |> ",
          if(sc %in% c("SC3","SC4","SC5"))"select(-ts15201, -subspell)",
          "",
          "bio <- left_join(bio, voctrain, by=c('ID_t', 'splink'))",
          "rm(voctrain)",
          "",
          "# 4. Expand to monthly structure for spell prioritisation -------------------------------------------",
          "",
          "# The expand function will generate one row for each month in the duration variable ('dur'). When we then group by ID_t and splink, we can generate a month variable (measured in months since january 1960) by taking the start date of each spell and adding the grouped row number (-1) to it. When respondents have reported parallel spells, this will lead to a dataset with duplicated months within person. Later, in step 5, the dataset is specifically ordered and then reduced to unique months, a process we call 'spell prioritisation.'",
          "bio <-  nepstools::expand(bio, dur)",
          "",
          "# Create indicator 'month' ",
          "bio <- bio |>",
          "  lazy_dt() |> # because of now very large data frame use this function from dtplyr for fastest R solution outside the data.table package",
          "  arrange(ID_t, splink) |>",
          "  group_by(ID_t, splink) |>",
          "  mutate(month = start + row_number() - 1) |>",
          "  ungroup() |>",
          "  as_tibble()",
          "",
          "# 5. Spell prioritisation process ----------------------------------------------------",
          "",
          "# To construct a person-year dataset where each row corresponds to one wave for each individual, a spell prioritisation process is useful for identifying the principal spell in cases where multiple spells occur simultaneously.",
          "",
          paste0("# We  may recode licences courses and ihk courses to value ", ifelse(sc != "SC5", "31", "37"), " to place it behind ", ifelse(sc != "SC5", "xmodule", "internship")," episodes in the prioritisation order, because these types of episodes are typically rather side spells than main spells and thus considered of lesser importance in many research projects with regard to spell prioritisation. You may change that."),
          "",
          "bio <- bio |>",
          "  mutate(prio = sptype,",
          paste0("  prio = ifelse(vt_typ %in% 13:14, ", ifelse(sc != "SC5", "31", "37"),", sptype),"),
          "  prio = case_when(",
          paste("  prio == ",prio_var[1]," ~ 1,"),
          paste("  prio == ",prio_var[2]," ~ 2,"),
          paste("  prio == ",prio_var[3]," ~ 3,"),
          paste("  prio == ",prio_var[4]," ~ 4,"),
          paste("  prio == ",prio_var[5]," ~ 5,"),
          paste("  prio == ",prio_var[6]," ~ 6,"),
          paste("  prio == ",prio_var[7]," ~ 7,"),
          paste("  prio == ",prio_var[8]," ~ 8,"),
          paste("  prio == ",prio_var[9]," ~ 9,"),
          paste("  prio == ",prio_var[10]," ~ 10,"),
          if(sc == "SC5")paste("  prio == ",prio_var[11]," ~ 11,"),
          "  TRUE ~ NA_real_  # For values not specified, set to NA",
          "))",
          "",
          "# Recode these 2 variables in order to use them in the prioritisation process (do it here due to speed issues later after the expanding).",
          "bio$spms[bio$spms == 2] <- 0",
          "bio$spms[is.na(bio$spms)] <- 0",
          "bio$worktime <- bio$ts23223",
          "bio$worktime[is.na(bio$ts23223)] <- 0",
          "",
          "# To prioritize multiple parallel spells, we consider multiple variables in the following order of relevance: prio, spms (main vs side episode), working hours, employment duration and splink. Edit if necessary.",
          "",
          "# Sort the data frame in this order",
          "bio$worktime <- as.numeric(bio$worktime) # as.numeric for sorting ",
          "bio$spms <- as.numeric(bio$spms) # as.numeric for sorting ",
          "bio <- bio[order(bio$ID_t, bio$month, bio$prio, -bio$spms, -bio$worktime, -bio$dur, bio$splink),]",
          "",
          if(parallel) gen_parallel_spells_r(format="harmonized"),
          "# Prioritisation: Remove duplicates, keeping only the first row for each group of combination of ID_t and month (base R here because its faster than dplyr solution with row_number()).",
          "bio <- bio[!duplicated(bio[c('ID_t', 'month')]), ]",
          "",
          "# Drop unnecessary variables",
          "bio <- bio |> select(-wave, -spms, -prio, -ts23223, -vt_typ) # drop wave variable from biography file here as there is only one wave for each episode which only indicates in which wave an episode was last reported, regardless of whether it was reported over multiple waves. In the next step the wave variable from cohort profile is added indicating all waves during which an episode was current.",
          "",
          if(work_exp)"# Generate work experience in months",
          if(work_exp)"bio <- bio  |> ",
          if(work_exp)  "group_by(ID_t)  |> ",
          if(work_exp)  "mutate(work_exp = sum(sptype == 26, na.rm = TRUE)) |>",
          if(work_exp)  "ungroup()",
          if(work_exp)"",
          if(unemp_exp)"# Generate unemployment experience in months",
          if(unemp_exp)"bio <- bio  |> ",
          if(unemp_exp)  "group_by(ID_t)  |> ",
          if(unemp_exp)  "mutate(unemp_exp = sum(sptype == 27, na.rm = TRUE)) |>",
          if(unemp_exp)  "ungroup()",
          if(unemp_exp)"",
          "# 6. Create person year format -------------------------------------",
          "",
          "# Finally we switch from a monthly format to a yearly format by taking the interview dates from cohort profile and left-joining the biography data to it.",
          "# This will keep only rows (months) in the bio dataset that correspond to actual interview dates from cohort profile. Finally this leads to a format with 1 row per year of a person where information is centered around each interview date.",
          "",
          "# Load interview dates from cohortprofile",
          "cohort_profile <- read_neps(paste0(datapath, '/', sc, '_CohortProfile_D_', suf_version,'.dta'), english = english)",
          "",
          "# Select Variables, generate a month variable for the interview date and filter for participation waves and non-NA month rows.",
          if(sc == "SC6")" cohort_profile <- cohort_profile |>
      select(ID_t, wave, tx8601y, tx8601m, tx80220) |>
      rename(tx8600m = tx8601m, tx8600y = tx8601y) |> # renaming date variables is only done for internal NEPScribe handling of different variable names across starting cohorts",
          if(sc %in% c("SC4", "SC5")) "cohort_profile <- cohort_profile |>
        select(ID_t, wave, tx8600y, tx8600m, tx80220) |> ",
          if(sc == "SC3") "cohort_profile <- cohort_profile |>
        select(ID_t, wave, tx8601y, tx8601m, tx80220) |>
        rename(tx8600m = tx8601m, tx8600y = tx8601y) |> # renaming date variables is only done for internal NEPScribe handling of different variable names across starting cohorts",
          "replace_values_with_na() |>",
          "mutate(month = ((tx8600y - 1960) * 12) + tx8600m - 1)  |>",
          "filter(tx80220 == 1 & !is.na(month)) |>",
          "select(-tx8600y, -tx8600m, -tx80220)",
          "",
          "# Inner join biography to cohort profile in order to keep only matches.",
          "bio <- inner_join(cohort_profile, bio, by=c('ID_t','month'))",
          "rm(cohort_profile)",
          "",
          "# Drop unnecessary vars",
          "bio <- bio |> ",
          "select(-worktime, -month, -splast)",
          "",
          if(length(datalist)>0) generate_strings(datalist, english, format = "harmonized"), # add variables feature
          if(length(datalist)>0) ""
        )

      if (education) {
        chapter <- chapter + 1
        scripts <- c(scripts, gen_qualification_prep_code_r(english, sc, chapter), "")
      }

      if (further_training) {
        chapter <- chapter + 1
        scripts <- c(scripts, further_training_gen_r(english, chapter), "")
      }

      if (children && sc %in% c("SC5", "SC6")) {
        chapter <- chapter + 1
        scripts <- c(scripts, gen_children_example_r_sc5_6(english, sc, chapter), "")
      }

      if (children && sc %in% c("SC3", "SC4")) {
        chapter <- chapter + 1
        scripts <- c(scripts, gen_children_example_r_sc3_4(english, sc, chapter), "")
      }

      if (set_missings) {
        chapter <- chapter + 1
        scripts <- c(
          scripts,
          paste0("# ", chapter, " Additional Settings------------------------------------"),
          "",
          "# set missings for all vars",
          "bio <- replace_values_with_na(bio)"
        )
      }

      }

      # NEPScribe R base script to transform NEPS SUF data from a spell format into a person-year structured format.
      # Harmonized biography spells are ignored; original spell files are used instead.

      if(dataformat== "R" & subformat == "Original Subspell Format"){
        chapter <- 3 + length(datalist)
        scripts <- c("# NEPScribe R base script to transform NEPS SUF data from a spell format into a person-year format.",
                     "# This is a basic data preparation script that generates a dataset in a person-year-format by taking the original sub-spell information from the NEPS SUF spell datasets as a baseline.",
                     "# Harmonized spells from the biography dataset are ignored.",
                     "",
                     "# !ATTENTION!",
                     "# Please carefully check each line and make sense of it. Edits to the script that fit your research project’s needs are probably necessary and recommended.",
                     "# Pay special attention to key variables of interest in the different sub-spells to see how these data have been collected and consider missings in sub-spells. Missings can be dealt with by replacing them with valid values from other sub-spells. Routines for that are partially provided in the script.",
                     "",
                     "# Approach:",
                     "",
                     "# 1. Step: Append all spell datasets into one dataset with the original sub-spell information.",
                     "",
                     "# 2. Step: Recode variables on the type of vocational training and working hours of employment. This information is used in the spell prioritisation process. Also recode start and end date information by replacing season codes and dropping spells with missing date information. At this point only sub-spells at the time of the interview date are kept (no harmonized information or sub-spells that weren’t current at the interview date).",
                     "",
                     "# 3. Step: Spell prioritisation process. Sorting of parallel spells is determined by spell order, main/side episode (descending), working hours (descending), duration (descending) and splink (ascending order in which the episodes were reported). You may edit this according to your research question(s). The dataset is then reduced to one (the first) spell per person and wave.",
                     "",
                     "# Additional data preparation steps may vary based on the settings configured in the Transform Data tab of the NEPScribe app.",
                     "",
                     "",
                     "rm(list = ls())",
                     "",
                     "# Load necessary libraries",
                     "list.of.packages <- c('dplyr','haven','lubridate','tidyr','dtplyr')",
                     "new.packages <- list.of.packages[!(list.of.packages %in% installed.packages()[,'Package'])] # check if required packages are in installed packages on this machine",
                     "if(length(new.packages)) install.packages (new.packages) # if new.packages contains sth and thus length is > 0, install those new packages",
                     "",
                     "# install nepstools if not installed (package needs to be installed seperately from github) ",
                     "if(!'nepstools' %in% installed.packages()) {",
                     " remotes::install_github('a-helbig/nepstools')",
                     "}",
                     "",
                     "# Add nepstools to list.of.packages",
                     "list.of.packages <- append(list.of.packages, 'nepstools')",
                     "",
                     "# Load all required packages of the given package liste above",
                     "invisible(lapply(list.of.packages, library, character.only = TRUE))",
                     "",
                     "",
                     "# Set working directory and define file paths (adjust as needed)",
                     if(nchar(datapath_local)>0) paste0("datapath = ","'",datapath_local,"/","'"),
                     if(nchar(datapath_local)==0)"datapath = \"\" # Specify local datapath here",
                     if(nchar(datapath_local)>0) paste0("suf_version = ", "'", suf_version,"'", " # Please adjust if necessary"),
                     if(nchar(datapath_local)==0)"suf_version = \"16-0-0\" # Please adjust if necessary",
                     paste0("english = ", english),
                     paste0("sc = ", "'",sc,"'"),
                     "",
                     "# Define variables",
                     "standard_spell_vars <- c('ID_t', 'splink', 'subspell', 'spell', 'spgen', 'spext', 'spstat', 'disagint', 'disagwave', 'wave', 'spms')",
                     "",
                     if(sc=="SC6")"keep_vars <- c('ts1111m', 'ts1111y', 'ts1112m', 'ts1112y', 'ts1112c','ts1311m', 'ts1311y', 'ts1312m', 'ts1312y', 'ts1312c','ts15201_v1', 'ts15201', 'ts1511m', 'ts1511y', 'ts1512m', 'ts1512y', 'ts1512c','ts2111m', 'ts2111y', 'ts2112m', 'ts2112y', 'ts2112c','ts23223_g1', 'ts2311m', 'ts2311y', 'ts2312m', 'ts2312y', 'ts2312c','ts2511m', 'ts2511y', 'ts2512m', 'ts2512y', 'ts2512c','ts2711m', 'ts2711y', 'ts2712m', 'ts2712y', 'ts2712c','ts2911m', 'ts2911y', 'ts2912m', 'ts2912y', 'ts2912c', 'sptype')",
                     if(sc %in% c("SC3", "SC4")) "keep_vars <- c('ts1111m', 'ts1111y', 'ts1112m', 'ts1112y', 'tf1112c','ts1311m', 'ts1311y', 'ts1312m', 'ts1312y', 'ts1312c', 'ts15201', 'ts1511m', 'ts1511y', 'ts1512m', 'ts1512y', 'ts1512c','ts2111m', 'ts2111y', 'ts2112m', 'ts2112y', 'ts2112c', 'ts23223', 'ts2311m', 'ts2311y', 'ts2312m', 'ts2312y', 'ts2312c','ts2511m', 'ts2511y', 'ts2512m', 'ts2512y', 'ts2512c','ts2711m', 'ts2711y', 'ts2712m', 'ts2712y', 'ts2712c','ts2911m', 'ts2911y', 'ts2912m', 'ts2912y', 'ts2912c', 'sptype')",
                     if(sc == "SC5") "keep_vars <- c('ts1111m', 'ts1111y', 'ts1112m', 'ts1112y', 'ts1112c','ts1311m', 'ts1311y', 'ts1312m', 'ts1312y', 'ts1312c', 'ts15201', 'ts1511m', 'ts1511y', 'ts1512m', 'ts1512y', 'ts1512c','ts2111m', 'ts2111y', 'ts2112m', 'ts2112y', 'ts2112c', 'ts23223', 'ts2311m', 'ts2311y', 'ts2312m', 'ts2312y', 'ts2312c','ts2511m', 'ts2511y', 'ts2512m', 'ts2512y', 'ts2512c','ts2711m', 'ts2711y', 'ts2712m', 'ts2712y', 'ts2712c','ts2911m', 'ts2911y', 'ts2912m', 'ts2912y', 'ts2912c', 'sptype')",
                     if(sc=='SC6')"spell_vars <- c('ts23223_g1', 'vt_typ') # working hours of employment and type of vocational training needed for later prioritization",
                     if(sc %in% c("SC3", "SC4","SC5"))"spell_vars <- c('ts23223', 'vt_typ') # working hours of employment and type of vocational training needed for later prioritization",
                     "",
                     "",
                     "# 1. Append spelldata files ----------------------------------------------------",
                     "",
                     "",
                     "# Load datasets",
                     "school <- read_neps(paste0(datapath, '/', sc, '_spSchool_D_', suf_version, '.dta'), english = english) |>",
                     "  mutate(sptype = 22)",
                     "",
                     "vocprep <- read_neps(paste0(datapath, '/', sc, '_spVocPrep_D_', suf_version, '.dta'), english = english) |>",
                     "  mutate(sptype = 23)",
                     "",
                     "voctrain <- read_neps(paste0(datapath, '/', sc,'_spVocTrain_D_', suf_version, '.dta'), english = english) |>",
                     "  mutate(sptype = 24)",
                     "",
                     "military <- read_neps(paste0(datapath, '/', sc,'_spMilitary_D_', suf_version, '.dta'), english = english) |>",
                     "  mutate(sptype = 25)",
                     "",
                     "emp <- read_neps(paste0(datapath, '/', sc, '_spEmp_D_', suf_version, '.dta'), english = english) |>",
                     "  mutate(sptype = 26)",
                     "",
                     "unemp <- read_neps(paste0(datapath, '/', sc, '_spUnemp_D_', suf_version, '.dta'), english = english) |>",
                     "  mutate(sptype = 27)",
                     "",
                     "parleave <- read_neps(paste0(datapath, '/', sc, '_spParLeave_D_', suf_version, '.dta'), english = english) |>",
                     "  mutate(sptype = 29)",
                     "",
                     "gap <- read_neps(paste0(datapath, '/', sc, '_spGap_D_', suf_version, '.dta'), english = english) |>",
                     "  mutate(sptype = 30)",
                     if(sc == "SC5")"internship <- read_neps(paste0(datapath, '/', sc, '_spInternship_D_', suf_version, '.dta'), english = english) |>",
                     "  mutate(sptype = 36)",
                     "",
                     "# Combine all datasets into one",
                     "bio <- bind_rows(",
                     "  school, vocprep, voctrain, ",
                     "  military, emp, unemp, ",
                     "  parleave, gap",
                     ")",
                     "",
                     "# After binding rows of numerical variables they lose their attached variable labels, so we reassign them.",
                     if(english)"attr(bio$ID_t, 'label') <- 'ID target '",
                     if(english)"attr(bio$splink, 'label') <- 'Link for spell merging'",
                     if(english)"attr(bio$subspell, 'label') <- 'Number of subspell'",
                     if(english)"attr(bio$spell, 'label') <- 'Spell number'",
                     if(english)"attr(bio$sptype, 'label') <- 'Spell type'",
                     if(!english)"attr(bio$ID_t, 'label') <- 'Target-ID '",
                     if(!english)"attr(bio$splink, 'label') <- 'Link fuer Spell-Merging'",
                     if(!english)"attr(bio$subspell, 'label') <- 'Teilepisodennummer'",
                     if(!english)"attr(bio$spell, 'label') <- 'Spell Nummer'",
                     if(!english)"attr(bio$sptype, 'label') <- 'Spell Typ'",
                     "",
                     "# Remove single spell data files",
                     "rm(school, vocprep, voctrain, ",
                     "   military, emp, unemp, ",
                     "   parleave, gap)",
                     "",
                     "# Keep only specified variables",
                     "bio <- bio  |> ",
                     "  select(all_of(standard_spell_vars), all_of(keep_vars))",
                     "",
                     "",
                     "# 2. Recoding and wrangling of variables required for spell prioritisation ----------",
                     "",
                     "",
                     if(sc=="SC6")"# We also require the type of vocational training for the prioritisation process of spells later in Step 5. Thus we recode type of voc. training by creating new variable vt_typ using ts15201_v1 (wave 1) and ts15201 (later waves). Then reduce to harmonized episodes (subspell==0).",
                     if(sc=="SC6")"suppressWarnings({ # warnings are suppressed here because case_match throws a warning due to conflicting variable labels in ts15201 and ts15201_v1. This doesnt matter, because in the new variable 'vt_typ' the variable labels from ts15201 are being used and that is preferable in most cases. Change this if neccessary.",
                     if(sc=="SC6")"  bio <- bio |>",
                     if(sc=="SC6")"    mutate(",
                     if(sc=="SC6")"      ts15201_v1 = case_match(",
                     if(sc=="SC6")"        ts15201_v1,",
                     if(sc=="SC6")"        # here the codes from the old voctrain-type var from wave 1 (ts15201_v1) are aligned with the new voctrain-type var ts15201 from wave 2+",
                     if(sc=="SC6")"        2 ~ 3,",
                     if(sc=="SC6")"        3 ~ 4,",
                     if(sc=="SC6")"        4 ~ 5,",
                     if(sc=="SC6")"        5 ~ 6,",
                     if(sc=="SC6")"        6 ~ 9,",
                     if(sc=="SC6")"        7 ~ 10,",
                     if(sc=="SC6")"        8 ~ 15,",
                     if(sc=="SC6")"        9 ~ 16,",
                     if(sc=="SC6")"        10 ~ 11,",
                     if(sc=="SC6")"        11 ~ 12,",
                     if(sc=="SC6")"        12 ~ 13,",
                     if(sc=="SC6")"        13 ~ 14,",
                     if(sc=="SC6")"        14 ~ 17,",
                     if(sc=="SC6")"        .default = ts15201_v1",
                     if(sc=="SC6")"      ),",
                     if(sc=="SC6")"      # Keep original value if not matched",
                     if(sc=="SC6")"      # Replace `ts15201` with recoded `ts15201_v1` where `ts15201` is -54 (wave 1)",
                     if(sc=="SC6")"      vt_typ = if_else(ts15201_v1 == -54, ts15201, ts15201_v1)",
                     if(sc=="SC6")"    ) |> #gen new var 'vt_typ' with values from both orginal vars",
                     if(sc=="SC6")"    select(-ts15201, -ts15201_v1)",
                     if(sc=="SC6")"})",
                     if(sc=="SC6")"",
                     if(sc %in% c("SC3","SC4","SC5"))"  bio <- bio |>",
                     if(sc %in% c("SC3","SC4","SC5"))"    mutate(vt_typ = ts15201) |>",
                     if(sc %in% c("SC3","SC4","SC5"))"    select(-ts15201)",
                     if(sc %in% c("SC3","SC4","SC5"))"",
                     "# Recode working hours",
                     if(sc=="SC6")"bio$ts23223_g1[bio$ts23223_g1 == -20] <- 90",
                     if(sc=="SC6")"bio$ts23223_g1[bio$ts23223_g1 == -21] <- NA",
                     if(sc %in% c("SC3","SC4","SC5"))"bio$ts23223[bio$ts23223 == -20] <- 90",
                     if(sc %in% c("SC3","SC4","SC5"))"bio$ts23223[bio$ts23223 == -21] <- NA",
                     "",
                     "# Drop harmonized spells",
                     "bio <- bio  |>  filter(!spstat %in% c(30, 31))",
                     "",
                     "# Note that spell variables may contain missing information across subspells. Therefore, we use tidyr::fill() to propagate non-missing values in the two recoded variables above, filling NAs with valid values from preceding or subsequent sub spells within the same episode (splink variable). Edit this, if you prefer a different approach.",
                     "",
                     "# First, set missing codes to NA on variables used for prioritisation later.",
                     "bio <- bio |>",
                     "  replace_values_with_na(vars = c(all_of(spell_vars)))",
                     "",
                     "bio <- bio |>",
                     "  dtplyr::lazy_dt() |> # because its a large data frame, we use this function from dtplyr for fastest R solution outside the data.table package.",
                     "  group_by(ID_t, splink)  |> ",
                     "  arrange(ID_t, splink, subspell)  |> ",
                     "  tidyr::fill(any_of(spell_vars), .direction = 'downup')  |> ",
                     "  ungroup() |>",
                     "  as_tibble()",
                     "",
                     "# Handle missing values (-98 and -97) by setting them to NA.",
                     "all_date_vars <- c('ts2911m','ts2311m','ts2111m','ts2711m','ts1511m','ts1111m','ts1311m','ts2511m','ts2312m','ts2912m','ts2112m','ts2712m','ts1512m','ts1112m','ts1312m','ts2512m','ts2911y','ts2311y','ts2111y','ts2711y','ts1511y','ts1111y','ts1311y','ts2511y','ts2312y','ts2912y','ts2112y','ts2712y','ts1512y','ts1112y','ts1312y','ts2512y')",
                     "bio <- replace_values_with_na(bio, vars=all_date_vars, values_to_replace=c(-97,-98))",
                     "",
                     "# Recode season codes in date variables",
                     "bio <- replace_season_codes(bio, vars = c('ts2911m','ts2311m','ts2111m','ts2711m','ts1511m','ts1111m','ts1311m','ts2511m','ts2312m','ts2912m','ts2112m','ts2712m','ts1512m','ts1112m','ts1312m','ts2512m'))",
                     "",
                     "# Create start and end variables in terms of months since reference year 1960.",
                     "bio <- bio  |> ",
                     "  # Create 'start' and 'end' as months since 1960, ensuring NA handling with coalesce",
                     "  mutate(",
                     "    start = ((ts2311y - 1960) * 12) + ts2311m - 1,",
                     "    start = coalesce(start, ((ts2911y - 1960) * 12) + ts2911m - 1),",
                     "    start = coalesce(start, ((ts2111y - 1960) * 12) + ts2111m - 1),",
                     "    start = coalesce(start, ((ts2711y - 1960) * 12) + ts2711m - 1),",
                     "    start = coalesce(start, ((ts1511y - 1960) * 12) + ts1511m - 1),",
                     "    start = coalesce(start, ((ts1111y - 1960) * 12) + ts1111m - 1),",
                     "    start = coalesce(start, ((ts1311y - 1960) * 12) + ts1311m - 1),",
                     "    start = coalesce(start, ((ts2511y - 1960) * 12) + ts2511m - 1),",
                     "    end = ((ts2312y - 1960) * 12) + ts2312m - 1,",
                     "    end = coalesce(end, ((ts2912y - 1960) * 12) + ts2912m - 1),",
                     "    end = coalesce(end, ((ts2112y - 1960) * 12) + ts2112m - 1),",
                     "    end = coalesce(end, ((ts2712y - 1960) * 12) + ts2712m - 1),",
                     "    end = coalesce(end, ((ts1512y - 1960) * 12) + ts1512m - 1),",
                     "    end = coalesce(end, ((ts1112y - 1960) * 12) + ts1112m - 1),",
                     "    end = coalesce(end, ((ts1312y - 1960) * 12) + ts1312m - 1),",
                     "    end = coalesce(end, ((ts2512y - 1960) * 12) + ts2512m - 1)",
                     "  ) |>",
                     "  # Filter out rows where start or end are NA",
                     "  filter(!is.na(start) & !is.na(end))  |> ",
                     "  # Calculate duration in months",
                     "  mutate(dur = end - start + 1)  |> ",
                     "  # Select and remove original date columns",
                     "  select(-c(ts2911m,ts2311m,ts2111m,ts2711m,ts1511m,ts1111m,ts1311m,ts2511m,ts2312m,ts2912m,ts2112m,ts2712m,ts1512m,ts1112m,ts1312m,ts2512m,",
                     "            ts2911y,ts2311y,ts2111y,ts2711y,ts1511y,ts1111y,ts1311y,ts2511y,ts2312y,ts2912y,ts2112y,ts2712y,ts1512y,ts1112y,ts1312y,ts2512y)) # Remove original date columns",
                     "",
                     "# Assign varlabels to variables",
                     if(english)"attr(bio$start, 'label') <- 'Start date'",
                     if(english)"attr(bio$end, 'label') <- 'End date'",
                     if(english)"attr(bio$dur, 'label') <- 'Duration'",
                     if(!english)"attr(bio$start, 'label') <- 'Startdatum'",
                     if(!english)"attr(bio$end, 'label') <- 'Enddatum'",
                     if(!english)"attr(bio$dur, 'label') <- 'Dauer'",
                     "",
                     "# Keep only spells on the interview date: all reported spells that ended before the corresponding interview date are dropped so that the person-year-format with one episode per year (interview) can be generated.",
                     "bio <- bio |> ",
                     if(sc %in% c("SC5","SC6"))"  filter(ts2312c == 1 | ts2912c == 1 | ts2112c == 1 | ts2712c == 1 | ts1512c == 1 | ts1112c == 1 | ts1312c == 1 | ts2512c == 1)",
                     if(sc %in% c("SC3","SC4"))"  filter(ts2312c == 1 | ts2912c == 1 | ts2112c == 1 | ts2712c == 1 | ts1512c == 1 | tf1112c == 1 | ts1312c == 1 | ts2512c == 1)",
                     "",
                     "# Drop revoked episodes from check module 30X",
                     "bio <- bio |> ",
                     "  filter(spms != -20)",
                     "",
                     "",
                     "# 3. Spell prioritisation: ----------------------------------------------------",
                     "",
                     "",
                     "# To construct a person-year dataset where each row corresponds to one wave for each individual, a spell prioritisation process is useful for identifying the principal spell in cases where multiple spells occur simultaneously.",
                     "",
                     "# prioritization of episode types following the order selected in NEPScribe",
                     paste0("# We  may recode licence courses and ihk courses to value ", ifelse(sc != "SC5", "31", "37"), " to place it behind ", ifelse(sc != "SC5", "xmodule", "internship")," episodes in the prioritisation order, because these types of episodes are typically rather side spells than main spells and thus considered of lesser importance in many research projects with regard to spell prioritisation. You may change that."),
                     "bio <- bio |>",
                     "  mutate(",
                     paste0("  prio = ifelse(vt_typ %in% 13:14, ", ifelse(sc != "SC5", "31", "37"),", sptype),"),
                     "  prio = case_when(",
                     paste("   prio == ",prio_var[1]," ~ 1,"),
                     paste("   prio == ",prio_var[2]," ~ 2,"),
                     paste("   prio == ",prio_var[3]," ~ 3,"),
                     paste("   prio == ",prio_var[4]," ~ 4,"),
                     paste("   prio == ",prio_var[5]," ~ 5,"),
                     paste("   prio == ",prio_var[6]," ~ 6,"),
                     paste("   prio == ",prio_var[7]," ~ 7,"),
                     paste("   prio == ",prio_var[8]," ~ 8,"),
                     paste("   prio == ",prio_var[9]," ~ 9,"),
                     paste("   prio == ",prio_var[10]," ~ 10,"),
                     if(sc == "SC5")paste("  prio == ",prio_var[11]," ~ 11,"),
                     "   TRUE ~ NA_real_  # For values not specified, set to NA",
                     "),",
                     "    spms = if_else(spms == -21, NA, spms),",
                     "    spms = tidyr::replace_na(spms, 0),",
                     "    spms = if_else(spms == 2, 0, spms),",
                     if(sc =="SC6")"    worktime = tidyr::replace_na(ts23223_g1, 0)",
                     if(sc %in% c("SC3","SC4","SC5"))"    worktime = tidyr::replace_na(ts23223, 0)",
                     "  )  |> ",
                     "# To prioritize parallel spells, we consider multiple variables in the following order of relevance: prio, spms (main vs side episode), working hours, employment duration and splink. Edit if necessary.",
                     "  arrange(ID_t, wave, prio, desc(spms), desc(worktime), desc(dur), splink)",
                     if(parallel) "",
                     if(parallel) gen_parallel_spells_r(format = "subspell"),
                     "",
                     "# Prioritize: Within each combination of ID_t and wave, keep only the first row according to the specified sorting order and therefore the observation with the highest prioritization per person and wave.",
                     "bio <- bio |> ",
                     "  lazy_dt() |> # use this function from dtplyr for faster processing",
                     "  group_by(ID_t, wave) |>",
                     "  filter(row_number() == 1) |>",
                     "  ungroup() |> ",
                     "  as_tibble()",
                     "",
                     "# Check for unique waves",
                     "if (any(duplicated(bio[c('ID_t', 'wave')]))) {",
                     "  stop('Duplicated waves found.')",
                     "}",
                     "",
                     "# Drop unnecessary variables",
                     "bio <- bio  |> ",
                     "  select(-starts_with('ts'), -prio, -spms, -starts_with('ts15201'))",
                     "",
                     if(length(datalist)>0) generate_strings(datalist, english, format = "subspell"), # add variables feature
                     if(length(datalist)>0) ""
        )

        if (education) {
          chapter <- chapter + 1
          scripts <- c(scripts, gen_qualification_prep_code_r(english, sc, chapter), "")
        }

        if (further_training) {
          chapter <- chapter + 1
          scripts <- c(scripts, further_training_gen_r(english, chapter), "")
        }

        if (children && sc %in% c("SC5", "SC6")) {
          chapter <- chapter + 1
          scripts <- c(scripts, gen_children_example_r_sc5_6(english, sc, chapter), "")
        }

        if (children && sc %in% c("SC3", "SC4")) {
          chapter <- chapter + 1
          scripts <- c(scripts, gen_children_example_r_sc3_4(english, sc, chapter), "")
        }

        if (set_missings) {
          chapter <- chapter + 1
          scripts <- c(
            scripts,
            paste0("# ", chapter, " Additional Settings------------------------------------"),
            "",
            "# set missings for all vars",
            "bio <- replace_values_with_na(bio)"
          )
        }

      }

      if(dataformat == "STATA" & subformat == "Harmonized Spell Format") {
        chapter <- 6 + length(datalist)
        scripts <- c(
          paste0("* NEPScribe base Stata Do-file to transform NEPS ", sc," SUF data into a person-year format"),
          "",
          "* This is a basic data preparation script that generates a dataset in a person-year-format by taking the harmonized spells from the NEPS SUF Biography file as a baseline.",
          "* !ATTENTION!",
          "* Please carefully check each line and make sense of it. Edits to the script that fit your research project’s needs are probably necessary and recommended.",
          "",
          "********************************************************************************",
          "* If you want access to within spell variation across waves, spell related longitudinal information should be merged via 'ID_t', 'wave' and 'splink' after step 6, when the person-year structure has been generated and after dropping harmonized episodes in the spell files.",
          "* When using the 'Additional variables' function in the NEPScribe app, this procedure is applied automatically. This ensures that time-varying spell information is preserved.",
          "* However, it requires careful handling of different missing value codes that arise from filtering or data issues.",
          "********************************************************************************",
          "",
          "* Approach:",
          "",
          "* 1. Step: Load the Biography dataset as a base for the person-year-dataset and compile start and end date and generate a duration variable.",
          "",
          "* 2. Step: Load the Employment dataset and merge it to the biography dataset to access the working hours variable. This variable will be used in step 6 for spell prioritisation of episode types.",
          "",
          "* 3. Step: Load the VocTrain dataset and merge it to the biography dataset to access the vocational training type variable. This variable will also be used in the spell prioritisation process.",
          "",
          "* 4. Step: Expand the data to a monthly format by multiplying each row of each respondent with the spell length in month (dur variable). This expansion to a month format is needed since there is no wave-specific information for episodes in the biography file but only one observation per episode with start and end date. To identify which episode represents the main activity at each interview date (and therefore wave) this reshape is needed. It serves as the basis for the spell prioritisation process in the next step.",
          "",
          "* 5. Step: Spell prioritisation process. Sort the months of each respondent by determined spell order, main/side episode (descending), working hours (descending), duration (descending) and splink (ascending order in which the episodes were reported). You may edit this according to your research question(s).",
          "",
          "* 6. Step: Reduce rows in dataset to interview date months by loading the CohortProfile dataset and generating a month variable for each interview date. Then merge this dataset and the biography data by ID_t and month. This leads to a dataset with one row per wave of each respondent (what we call: 'person-year-dataset').",
          "",
          "* Additional data preparation steps may vary based on the settings configured in the Transform Data tab of the NEPScribe app.",
          "",
          "********************************************************************************",
          "clear",
          "set more off",
          "",
          if(english)"*install nepstools ado in order to be able to switch language",
          if(english)"net install nepstools, from(http://nocrypt.neps-data.de/stata)",
          if(english)"",
          "* paths ",
          if(nchar(datapath_local)>0)paste0("global DATA ","\"",datapath_local,"/","\""),
          if(nchar(datapath_local)==0)"global DATA = \"\" // Specify local datapath here",
          if(nchar(datapath_local)>0)paste0("global suf ", "\"",suf_version, "\"", " // Please adjust if necessary"),
          if(nchar(datapath_local)==0)"global suf \"16-0-0\" // Please specify, e.g. 16-0-0",
          "",
          "",
          "********************************************************************************",
          "* 1. Base: biography file",
          "********************************************************************************",
          "",
          "* We take the harmonized episodes from the biography file as a baseline for our person-year dataset.",
          paste0("use \"$DATA\\", sc, "_Biography_D_$suf.dta\", clear"),
          "mvdecode _all, mv(-98 -97 -54 -55 = .)",
          "",
          "* Date variables",
          "gen start=ym(starty, startm)",
          "gen end=ym(endy, endm)",
          "drop startm starty endm endy",
          "",
          "format start end %tm",
          if (!english)"lab var start \"Startdatum in Monaten seit Jan 1960\"",
          if (!english)"lab var end \"Enddatum in Monaten seit Jan 1960\"",
          "",
          "drop if start == . | end == .",
          "",
          "* Duration",
          "gen dur = end-start+1",
          "sum dur, detail // no negative values",
          if (!english)"label var dur \"Dauer des Spells\"",
          "",
          "isid ID_t splink // assure that there is only one observation per person and episode",
          "",
          "********************************************************************************",
          "* 2. Employment info for spell priorization",
          "********************************************************************************",
          "",
          "* We need the working hours for the prioritisation process of parallel employment spells later in Step 5. Thus we merge employment data, recode working hours and reduce to harmonized episodes (subspell==0) and join it to biography data.",
          "",
          "preserve",
          "",
          paste0("use \"$DATA\\", sc, "_spEmp_D_$suf.dta\", clear"),
          if(sc == "SC6") "keep ID_t splink spell subspell ts23223_g1 ",
          if(sc == "SC6") "rename ts23223_g1 ts23223" else "keep ID_t splink spell subspell ts23223",
          "",
          "recode ts23223 (-20 = 90) (-21 = .)",
          "",
          "* Keep only harmonized spells - necessary in order to merge it to biography via ID_t and splink",
          "keep if subspell == 0",
          "",
          "tempfile emp",
          "save `emp'",
          "",
          "restore",
          "",
          "merge 1:1 ID_t splink using `emp', keep(1 3) nogen",
          "",
          "********************************************************************************",
          "* 3. Voc train info for spell priorization",
          "********************************************************************************",
          "",
          "* We also require the type of vocational training for the prioritisation process of spells later in Step 5. Thus we merge voctrain data and recode type of voc. training by creating new variable vt_typ using ts15201_v1 (wave 1) and ts15201 (later waves). Then reduce to harmonized episodes (subspell==0) and join it to biography data.",
          "",
          "preserve",
          "",
          paste0("use \"$DATA\\", sc, "_spVocTrain_D_$suf.dta\", clear"),
          if(sc=="SC6") "keep ID_t splink subspell ts15201_v1 ts15201" else "keep ID_t splink subspell ts15201",
          "",
          if(sc=="SC6")"* harmonize type of voctraining",
          if(sc=="SC6")"* first we need to align the codes of both variables because they differ unfortunately",
          if(sc=="SC6")"clonevar vt_typ_v1 = ts15201_v1",
          if(sc=="SC6")"recode vt_typ_v1 (2=3) (3=4) (4=5) (5=6) (6=9) (7=10) (8=15) (9=16) (10=11) (11=12) (12=13) (13=14) (14=17)",
          if(sc=="SC6")"label define de1876 15 \"Promotion\" 16 \"Habilitation\" 17 \"eine andere Ausbildung\", modify",
          if(sc=="SC6")"clonevar vt_typ = ts15201",
          if(sc=="SC6")"replace vt_typ = vt_typ_v1 if vt_typ == -54 ",
          "",
          if(sc %in% c("SC3","SC4","SC5"))"rename ts15201 vt_typ",
          "",
          "* Keep only harmonized spells",
          "keep if subspell == 0 ",
          "",
          if(sc=="SC6")"drop ts15201_v1 ts15201 vt_typ_v1",
          "tempfile vt",
          "save `vt'",
          "",
          "restore",
          "merge 1:1 ID_t splink using `vt', keep(1 3) nogen",
          "",
          "********************************************************************************",
          "* 4. Expand dataframe to 'months-structure' for spell prioritisation",
          "********************************************************************************",
          "",
          "* Using expand  will generate one row for each month in the duration variable ('dur'). When we then group by ID_t and splink, we can generate a month variable (measured in months since january 1960) by taking the start date of each spell and adding the grouped row number (-1) to it. When respondents have reported parallel spells, this will lead to a dataset with duplicated months within persons. Later, in step 5, the dataset is specifically ordered and then reduced to unique months, a process we call 'spell prioritisation.",
          "expand dur",
          "",
          "sort ID_t splink",
          "",
          "bys ID_t splink: gen n = _n -1",
          "",
          "gen month = start + n",
          "format month %tm",
          "",
          "drop n",
          "",
          "********************************************************************************",
          "* 5. Spell prioritisation",
          "********************************************************************************",
          "",
          "* To construct a person-year dataset where each row corresponds to one wave for each individual, a spell prioritisation process is useful for identifying the principal spell in cases where multiple spells occur simultaneously.",
          "",
          "* To prioritize multiple parallel employment spells, we consider multiple variables in the following order of relevance: priolist (prioritization of episode types from NEPScribe), spms (main vs side episode), working hours, employment duration and splink",
          "* sort parallel Episodes",
          "clonevar prio = sptype",
          "",
          paste0("* recode licences courses and ihk courses to value ",  ifelse(sc != "SC5", "31", "37"), " to place it behind ", ifelse(sc != "SC5", "xmodule", "internship"), " episodes in the prioritisation order because these types of episodes are considered of minor importance in many research projects in regard to spell prioritisation."),
          paste0("recode prio 24 = ", ifelse(sc != "SC5", "31", "37"), " if inrange(vt_typ,13,14)"),
          "",
          if(sc != "SC5")paste0("recode prio ","(",prio_var[1],  " = 1)"," (",prio_var[2]," = 2)"," (",prio_var[3]," = 3)"," (",prio_var[4]," = 4)"," (",prio_var[5]," = 5)"," (",prio_var[6]," = 6)"," (",prio_var[7]," = 7)"," (",prio_var[8]," = 8)"," (",prio_var[9]," = 9)"," (",prio_var[10]," = 10)"),
          if(sc == "SC5")paste0("recode prio ","(",prio_var[1],  " = 1)"," (",prio_var[2]," = 2)"," (",prio_var[3]," = 3)"," (",prio_var[4]," = 4)"," (",prio_var[5]," = 5)"," (",prio_var[6]," = 6)"," (",prio_var[7]," = 7)"," (",prio_var[8]," = 8)"," (",prio_var[9]," = 9)"," (",prio_var[10]," = 10)"," (",prio_var[11]," = 11)"),
          "* For sorting set side episodes und missings to 0",
          "recode spms (1 = 1) (2 . .x = 0)",
          "",
          "clonevar worktime = ts23223",
          "replace worktime = 0 if missing(ts23223) //recode missings to 0 for sorting",
          "",
          "gsort ID_t month prio -spms -worktime -dur splink // this is the overall prioritisation order",
          "",
          if(parallel) gen_parallel_spells_stata(format="harmonized"),
          "* Reduce to the prioritized spells by only keeping the first observation of each month within each individual",
          "by ID_t month: keep if _n == 1",
          "drop worktime prio wave ts23223 vt_typ // drop wave variable from biography file here as there is only one wave for each episode which only indicates in which wave an episode was last reported, regardless of whether it was reported over multiple waves. In the next step the wave variable from cohort profile is added indicating all waves during which an episode was current.",
          "",
          if(work_exp)"* Generate work experience in months",
          if(work_exp)"gen emp=1 if sptype == 26",
          if(work_exp)"bys ID_t: gen work_exp = sum(emp)",
          if(work_exp)"",
          if(unemp_exp)"* Generate unemployment experience in months",
          if(unemp_exp)"gen unemp=1 if sptype == 27",
          if(unemp_exp)"bys ID_t: gen unemp_exp = sum(unemp)",
          if(unemp_exp)"",
          "********************************************************************************",
          "* 6. Create person year format",
          "********************************************************************************",
          "",
          "* Finally we switch from a monthly format to a yearly format by taking the interview dates from cohort profile, merging it to the biography data, while keeping only matches.",
          "* This will keep only rows (months) in the bio dataset that correspond to actual interview dates from cohort profile. Finally this leads to a format with 1 row per year of a person where information is centered around each interview date.",
          "",
          "* Load interview dates from cohortprofile",
          "preserve",
          paste0("use \"$DATA\\", sc, "_CohortProfile_D_$suf.dta\", clear"),
          "",
          if(sc %in% c("SC3", "SC6"))"keep ID_t wave tx8601y tx8601m tx80220",
          if(sc %in% c("SC4", "SC5"))"keep ID_t wave tx8600y tx8600m tx80220",
          "",
          "* Gen interview month",
          if(sc %in% c("SC3", "SC6"))"gen month = ym(tx8601y,tx8601m)",
          if(sc %in% c("SC4", "SC5"))"gen month = ym(tx8600y,tx8600m)",
          "format month %tm",
          "",
          if (!english) "label var month \"Monat\"",
          "",
          "* Drop non-participants",
          "drop if tx80220 != 1 | missing(month)",
          "",
          if(sc == "SC5") "*Drop wave duplicates in order to be able to merge it to the biography data from before",
          if(sc == "SC5") "bys ID_t month: gen n = _n",
          if(sc == "SC5") "drop if n > 1",
          if(sc == "SC5") "drop n",
          if(sc == "SC5") "",
          if(sc %in% c("SC3", "SC6"))"drop tx8601y tx8601m tx80220",
          if(sc %in% c("SC4", "SC5"))"drop tx8600y tx8600m tx80220",
          "",
          "tempfile intd",
          "save `intd'",
          "",
          "restore",
          "",
          "merge 1:1 ID_t month using `intd', nogen keep(match)",
          "",
          if(length(datalist)>0) generate_strings_stata(datalist, format = "harmonized"), # add variables feature
          if(length(datalist)>0) ""
        )

        if (education) {
          chapter <- chapter + 1
          scripts <- c(scripts, gen_qualification_prep_code_stata(english, sc, chapter), "")
        }

        if (further_training) {
          chapter <- chapter + 1
          scripts <- c(scripts, further_training_gen_stata(english, chapter), "")
        }

        if (children && sc %in% c("SC5", "SC6")) {
          chapter <- chapter + 1
          scripts <- c(scripts, gen_children_example_stata_sc5_6(english, sc, chapter), "")
        }

        if (children && sc %in% c("SC3", "SC4")) {
          chapter <- chapter + 1
          scripts <- c(scripts, gen_children_example_stata_sc3_4(english, sc, chapter), "")
        }

        if (set_missings || english) {
          chapter <- chapter + 1
          scripts <- c(
            scripts,
            paste0("********************************************************************************"),
            paste0("* ", chapter, " Additional Settings"),
            paste0("********************************************************************************")
          )
        }

        if (set_missings) {
          scripts <- c(
            scripts,
            "",
            "* Set missings for all variables",
            "mvdecode _all, mv(-98 = .a \\ -97 = .b \\ -54 = .c \\ -55 = .d ) // alternatively one can use the 'nepsmiss' function from nepstools ado",
            ""
          )
        }

        if (english) {
          scripts <- c(
            scripts,
            "",
            "* Switch variable and value labels to english",
            "label language en",
            "",
            if (english) "label var start \"Date of episode start (in months since january 1960)\"",
            if (english) "label var end \"Date of episode end (months since january 1960)\"",
            if (english) "label var dur \"Duration of episode\"",
            if (english) "label var month \"Month\""
          )
        }

      }


      if(dataformat == "STATA" & subformat == "Original Subspell Format"){
        chapter <- 3 + length(datalist)
        scripts <- c(
          "* NEPScribe base Stata Do-file to transform NEPS SUF data from a spell format into a person-year format.",
          "* This is a basic data preparation script that generates a dataset in a person-year-format by taking the original sub-spell information from the NEPS SUF spell datasets as a baseline. Harmonized spells from the biography dataset are ignored.",
          "",
          "* !ATTENTION!",
          "* Please carefully check each line and make sense of it. Edits to the script that fit your research project’s needs are probably necessary and recommended.",
          "* Pay special attention to key variables of interest in the different sub-spells to see how these data have been collected and consider missings in sub-spells. Missings can be dealt with by replacing them with valid values from other sub-spells. Routines for that are partially provided in the script.",
          "",
          "********************************************************************************",
          "* Approach:",
          "",
          "* 1. Step: Append all spell datasets into one dataset with the original sub-spell information.",
          "",
          "* 2. Step: Recode variables on the type of vocational training and working hours of employment. This information is used in the spell prioritisation process. Also recode start and end date information by replacing season codes and dropping spells with missing date information. At this point only sub-spells at the time of the interview date are kept (no harmonized information or sub-spells that weren’t current at the interview date).",
          "",
          "* 3. Step: Spell prioritisation process. Sorting of parallel spells is determined by spell order, main/side episode (descending), working hours (descending), duration (descending) and splink (ascending order in which the episodes were reported). You may edit this according to your research question(s). The dataset is then reduced to one (the first) spell per person and wave.",
          "",
          "* Additional data preparation steps may vary based on the settings configured in the Transform Data tab of the NEPScribe app.",
          "",
          "********************************************************************************",
          "",
          "clear",
          "set more off",
          "",
          if(english==T)"*Install nepstools ado in order to be able to switch language",
          if(english==T)"net install nepstools, from(http://nocrypt.neps-data.de/stata)",
          if(english==T)"",
          "* paths ",
          if(nchar(datapath_local)>0)paste0("global DATA ","\"",datapath_local,"/","\""),
          if(nchar(datapath_local)==0)"global DATA = \"\" // Specify local datapath here",
          if(nchar(datapath_local)>0)paste0("global suf ", "\"",suf_version, "\"", " // Please adjust if necessary"),
          if(nchar(datapath_local)==0)"global suf \"\" // Please specify, e.g. 16-0-0",
          "",
          "global standard_spell_vars ID_t splink subspell spell spgen spext spstat disagint disagwave wave spms sptype",
          if(sc == "SC6")"global keep_vars ts1111m ts1111y ts1112m ts1112y ts1112c ts1311m ts1311y ts1312m ts1312y ts1312c ts1511m ts1511y ts1512m ts1512y ts1512c ts2111m ts2111y ts2112m ts2112y ts2112c  ts2311m ts2311y ts2312m ts2312y ts2312c ts2511m ts2511y ts2512m ts2512y ts2512c  ts2711m ts2711y ts2712m ts2712y  ts2712c ts2911m ts2911y ts2912m ts2912y ts2912c ts23223_g1 ts15201_v1 ts15201",
          if(sc %in% c("SC3","SC4"))"global keep_vars ts1111m ts1111y ts1112m ts1112y tf1112c ts1311m ts1311y ts1312m ts1312y ts1312c ts1511m ts1511y ts1512m ts1512y ts1512c ts2111m ts2111y ts2112m ts2112y ts2112c  ts2311m ts2311y ts2312m ts2312y ts2312c ts2511m ts2511y ts2512m ts2512y ts2512c  ts2711m ts2711y ts2712m ts2712y  ts2712c ts2911m ts2911y ts2912m ts2912y ts2912c ts15201 ts23223",
          if(sc == "SC5")"global keep_vars ts1111m ts1111y ts1112m ts1112y ts1112c ts1311m ts1311y ts1312m ts1312y ts1312c ts1511m ts1511y ts1512m ts1512y ts1512c ts2111m ts2111y ts2112m ts2112y ts2112c  ts2311m ts2311y ts2312m ts2312y ts2312c ts2511m ts2511y ts2512m ts2512y ts2512c  ts2711m ts2711y ts2712m ts2712y  ts2712c ts2911m ts2911y ts2912m ts2912y ts2912c ts15201 ts23223",
          if(sc == "SC6")"global spell_vars ts23223_g1 vt_typ // working hours of employment and type of vocational training needed for later prioritization",
          if(sc %in% c("SC3","SC4","SC5"))"global spell_vars ts23223 vt_typ // working hours of employment and type of vocational training needed for later prioritization",
          "",
          "*************************************************************************",
          "  * 1. Append spelldata files",
          "*************************************************************************",
          "",
          paste0("use \"$DATA\\", sc, "_spSchool_D_$suf.dta\", clear"),
          "gen sptype = 22",
          "",
          paste0("append using \"$DATA\\", sc, "_spVocPrep_D_$suf.dta\""),
          "replace sptype = 23 if sptype == .",
          "",
          paste0("append using \"$DATA\\", sc, "_spVocTrain_D_$suf.dta\""),
          "replace sptype = 24 if sptype == .",
          "",
          paste0("append using \"$DATA\\", sc, "_spMilitary_D_$suf.dta\""),
          "replace sptype = 25 if sptype == .",
          "",
          paste0("append using \"$DATA\\", sc, "_spEmp_D_$suf.dta\""),
          "replace sptype = 26 if sptype ==.",
          "",
          paste0("append using \"$DATA\\", sc, "_spUnemp_D_$suf.dta\""),
          "replace sptype = 27 if sptype == .",
          "",
          paste0("append using \"$DATA\\", sc, "_spParLeave_D_$suf.dta\""),
          "replace sptype = 29 if sptype == .",
          "",
          paste0("append using \"$DATA\\", sc, "_spGap_D_$suf.dta\""),
          "replace sptype = 30 if sptype == .",
          "",
          if(sc == "SC5") paste0("append using \"$DATA\\", sc, "_spInternship_D_$suf.dta\""),
          "replace sptype = 36 if sptype == .",
          "",
          "label var sptype \"spelltype\"",
          "label define sptype 22 \"school\" 23 \"vocprep\" 24 \"voctrain\" 25 \"military\" 26 \"employment\" 27 \"unemp\" 29 \"parleave\" 30 \"gap\" 36 \"internship\"",
          "label val sptype sptype",
          "",
          "* keep only specified vars",
          "keep $standard_spell_vars $keep_vars ",
          "",
          "*************************************************************************",
          "* 2. Recoding and wrangling of variables required for spell prioritisation",
          "*************************************************************************",
          "",
          if(sc=="SC6")"* harmonizing the type of vocational training.",
          if(sc=="SC6")"* first we need to align the codes of both variables because they unfortunately differ.",
          if(sc=="SC6")"clonevar vt_typ_v1 = ts15201_v1",
          if(sc=="SC6")"recode vt_typ_v1 (2=3) (3=4) (4=5) (5=6) (6=9) (7=10) (8=15) (9=16) (10=11) (11=12) (12=13) (13=14) (14=17)",
          if(sc=="SC6")"label define de1876 15 \"Promotion\" 16 \"Habilitation\" 17 \"eine andere Ausbildung\", modify",
          if(sc=="SC6")"clonevar vt_typ = ts15201",
          if(sc=="SC6")"replace vt_typ = vt_typ_v1 if vt_typ == -54 ",
          if(sc=="SC6")"drop vt_typ_v1 ts15201 ts15201_v1",
          if(sc %in% c("SC3","SC4","SC5")) "rename ts15201 vt_typ",
          "",
          "* Working hours recoding",
          if(sc=="SC6")"recode ts23223_g1 (-20 = 90) (-21 = .)",
          if(sc %in% c("SC3","SC4","SC5"))"recode ts23223 (-20 = 90) (-21 = .)",
          "* Drop harmonized spells",
          "drop if inlist(spstat,30,31)",
          "",
          "* Note that spell variables may contain missing information across sub spells. Therefore, we fill missings in the two recoded variables above with valid values from preceding or subsequent sub spells. Edit this, if you prefer a different approach.",
          "* First, set missings on variables used for prioritisation later. It is recommended to use the function nepsmiss from the nepstools ado to recode all missing values to specific missing codes. You may install it with: net install nepstools, from(http://nocrypt.neps-data.de/stata). If you want to exclude specific missings from being recoded you might use statas mvdecode function instead.",
          "nepsmiss _all",
          "",
          "foreach var of varlist $spell_vars  {",
          "  bys ID_t splink (subspell): replace `var' = `var'[_n-1] if missing(`var') & !missing(`var'[_n-1]) //fill missings from preceding rows",
          "  bys ID_t splink (subspell): replace `var' = `var'[_n+1] if missing(`var') & !missing(`var'[_n+1]) //fill missings from subsequent rows",
          "}",
          "",
          "* Generate date variable from actual respondent information (_g date variables have problems)",
          "* First, recode season codes in date variables",
          "foreach var of varlist ts2311m ts2312m ts2911m ts2912m ts2111m ts2112m ts2711m ts2712m ts1511m ts1512m ts1111m ts1112m ts1311m ts1312m ts2511m ts2512m {",
          "	recode `var' (21=1) (24=4) (27=7) (30=10) (32=12)",
          "}",
          "",
          "* Gen startdate variable",
          "gen start=ym(ts2311y, ts2311m) // Emp",
          "replace start = ym(ts2911y, ts2911m) if start == . // Gap",
          "replace start = ym(ts2111y, ts2111m) if start == . // Military",
          "replace start = ym(ts2711y, ts2711m) if start == . // ParLeave",
          "replace start = ym(ts1511y, ts1511m) if start == . // VocTrain",
          "replace start = ym(ts1111y, ts1111m) if start == . // School",
          "replace start = ym(ts1311y, ts1311m) if start == . // VocPrep",
          "replace start = ym(ts2511y, ts2511m) if start == . // Unemp",
          "",
          "* gen enddate variable",
          "gen end=ym(ts2312y, ts2312m) // Emp",
          "replace end = ym(ts2912y, ts2912m) if end == . // Gap",
          "replace end = ym(ts2112y, ts2112m) if end == . // Military",
          "replace end = ym(ts2712y, ts2712m) if end == . // ParLeave",
          "replace end = ym(ts1512y, ts1512m) if end == . // VocTrain",
          "replace end = ym(ts1112y, ts1112m) if end == . // School",
          "replace end = ym(ts1312y, ts1312m) if end == . // VocPrep",
          "replace end = ym(ts2512y, ts2512m) if end == . // Unemp",
          "",
          "* Format this var",
          "format start %tm",
          "format end %tm ",
          if (!english)"lab var start \"Startdatum in Monaten seit Jan 1960\"",
          if (!english)"lab var end \"Enddatum in Monaten seit Jan 1960\"",
          "",
          "* Drop spells with missing dates ",
          "drop if start == . | end == .",
          "",
          "* Duration",
          "gen dur = end-start+1",
          "sum dur, detail // no negative values",
          if (!english)"label var dur \"Dauer des Spells\"",
          "",
          "* Keep only spells on the interview date: all reported spells that ended before the corresponding interview date are dropped so that the person-year-format with one episode per year (interview) can be generated.",
          "gen keep = .",
          if(sc %in% c("SC3","SC4")) "foreach var of varlist ts2312c ts2912c ts2112c ts2712c ts1512c tf1112c ts1312c ts2512c {",
          if(sc %in% c("SC6","SC5")) "foreach var of varlist ts2312c ts2912c ts2112c ts2712c ts1512c ts1112c ts1312c ts2512c {",
          "  replace keep = 1 if `var' == 1",
          "}",
          "keep if keep == 1",
          "drop keep",
          "",
          "* Drop revoked episodes from check module 30X",
          "drop if spms == .y",
          "",
          "sort ID_t wave sptype",
          "",
          "*************************************************************************",
          "* 3. Spell prioritisation",
          "*************************************************************************",
          "",
          "* To prioritize multiple parallel employment spells, we consider multiple variables in the following order of relevance: priolist (prioritization of episode types from NEPScribe), spms (main vs side episode from biography), working hours, employment duration and splink.",
          "* Sort parallel Episodes",
          "clonevar prio = sptype",
          "",
          paste0("* recode licences courses and ihk courses to value ",  ifelse(sc != "SC5", "31", "37"), " to place it behind ", ifelse(sc != "SC5", "xmodule", "internship"), " episodes in the prioritisation order because these types of episodes are considered of minor importance in many research projects in regard to spell prioritisation."),
          paste0("recode prio 24 = ", ifelse(sc != "SC5", "31", "37"), " if inrange(vt_typ,13,14)"),
          "",
          "* Prioritization of episodes following the order selected in NEPScribe",
          if(sc != "SC5")paste0("recode prio ","(",prio_var[1],  " = 1)"," (",prio_var[2]," = 2)"," (",prio_var[3]," = 3)"," (",prio_var[4]," = 4)"," (",prio_var[5]," = 5)"," (",prio_var[6]," = 6)"," (",prio_var[7]," = 7)"," (",prio_var[8]," = 8)"," (",prio_var[9]," = 9)"," (",prio_var[10]," = 10)"),
          if(sc == "SC5")paste0("recode prio ","(",prio_var[1],  " = 1)"," (",prio_var[2]," = 2)"," (",prio_var[3]," = 3)"," (",prio_var[4]," = 4)"," (",prio_var[5]," = 5)"," (",prio_var[6]," = 6)"," (",prio_var[7]," = 7)"," (",prio_var[8]," = 8)"," (",prio_var[9]," = 9)"," (",prio_var[10]," = 10)"," (",prio_var[11]," = 11)"),
          "* For sorting set side episodes and missings to 0",
          "recode spms (1 = 1) (2 . = 0)",
          "",
          if(sc=="SC6")"clonevar worktime = ts23223_g1",
          if(sc=="SC6")"replace worktime = 0 if missing(ts23223_g1) //recode missings to 0 for gsorting",
          if(sc %in% c("SC3","SC4","SC5")) "clonevar worktime = ts23223",
          if(sc %in% c("SC3","SC4","SC5")) "replace worktime = 0 if missing(ts23223) //recode missings to 0 for gsorting",
          "",
          "* Gsort them in the following order. This order is our prioritisation rule in the following order of importance: ID_t, wave, spelltype, main or side spell, working hours, duration of episode, splink (order of spell collection).",
          "gsort ID_t wave prio -spms -worktime -dur splink",
          "",
          if(parallel) gen_parallel_spells_stata(format = "subspell"),
          "* Reduce to the prioritized spells by only keeping the first observation of each wave within each individual.",
          "by ID_t wave: keep if _n == 1",
          "",
          "* Check for unique waves",
          "isid ID_t wave",
          "",
          "*drop vars that are not required anymore.",
          if(sc %in% c("SC3","SC4"))"drop ts1111m ts1111y ts1112m ts1112y tf1112c ts1311m ts1311y ts1312m ts1312y ts1312c ts1511m ts1511y ts1512m ts1512y ts1512c ts2111m ts2111y ts2112m ts2112y ts2112c ts2311m ts2311y ts2312m ts2312y ts2312c ts2511m ts2511y ts2512m ts2512y ts2512c ts2711m ts2711y ts2712m ts2712y ts2712c ts2911m ts2911y ts2912m ts2912y ts2912c prio worktime",
          if(sc %in% c("SC5","SC6"))"drop ts1111m ts1111y ts1112m ts1112y ts1112c ts1311m ts1311y ts1312m ts1312y ts1312c ts1511m ts1511y ts1512m ts1512y ts1512c ts2111m ts2111y ts2112m ts2112y ts2112c ts2311m ts2311y ts2312m ts2312y ts2312c ts2511m ts2511y ts2512m ts2512y ts2512c ts2711m ts2711y ts2712m ts2712y ts2712c ts2911m ts2911y ts2912m ts2912y ts2912c prio worktime",
          "",
          if(length(datalist)>0) generate_strings_stata(datalist, format = "subspell"), # add variables feature
          if(length(datalist)>0)""
        )

        if (education) {
          chapter <- chapter + 1
          scripts <- c(scripts, gen_qualification_prep_code_stata(english, sc, chapter), "")
        }

        if (further_training) {
          chapter <- chapter + 1
          scripts <- c(scripts, further_training_gen_stata(english, chapter), "")
        }

        if (children && sc %in% c("SC5", "SC6")) {
          chapter <- chapter + 1
          scripts <- c(scripts, gen_children_example_stata_sc5_6(english, sc, chapter), "")
        }

        if (children && sc %in% c("SC3", "SC4")) {
          chapter <- chapter + 1
          scripts <- c(scripts, gen_children_example_stata_sc3_4(english, sc, chapter), "")
        }

        if (set_missings || english) {
          chapter <- chapter + 1
          scripts <- c(
            scripts,
            paste0("********************************************************************************"),
            paste0("* ", chapter, " Additional Settings"),
            paste0("********************************************************************************")
          )
        }

        if (set_missings) {
          scripts <- c(
            scripts,
            "",
            "* Set missings for all variables",
            "mvdecode _all, mv(-98 = .a \\ -97 = .b \\ -54 = .c \\ -55 = .d ) // alternatively one can use the 'nepsmiss' function from nepstools ado",
            ""
          )
        }

        if (english) {
          scripts <- c(
            scripts,
            "",
            "* Switch variable and value labels to english",
            "label language en",
            "",
            if (english) "label var start \"Date of episode start (in months since january 1960)\"",
            if (english) "label var end \"Date of episode end (months since january 1960)\"",
            if (english) "label var dur \"Duration of episode\""
          )
        }

      }
      return(scripts)
    }

